version: '3'
services:

  music-recommender-api:
    build: ./backend
    container_name: music-recommender-api
    ports:
      - 5000:80
    environment:
      - SpotifyClientCredentials__ClientId=
      - SpotifyClientCredentials__ClientSecret=
      
  music-recommender-web:
    build: ./web
    container_name: music-recommender-web
    ports:
      - 3000:3000
    links:
      - music-recommender-api